//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConToDbaseScaffolding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyErieTemp3
    {
        public int TempID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string Temp { get; set; }
    }
}
